### ISSUE TITLE
关于checkpoint打开403的情况

### ISSUE THREAD

**Issue by Missingkey** [xlxwalex/FCGEC#12]
您好！今天打开checkpoint网页发现403了，请问可以修复嘛

**Comment by xlxwalex** [comment]
您好，
  如果是浏览器打开403，你可以刷新一下网页就能进入下载（绝大多数浏览器）。如果不行的话可以直接复制网址用下载器下载，可以参考一下ISSUE #2 ，如果还是不行，欢迎回复
