### ISSUE TITLE
Single-sentence text inference directly using FCGEC-Joint

### ISSUE THREAD

**Issue by yuan-cherish** [xlxwalex/FCGEC#15]
Hello, I have finished predicting the test set according to the steps you provided, but now I want to predict only one line of text how to do it? Obviously the prediction steps you provided are a bit too responsible, can I just use Forwardl of FCGEC-Joint to fix a single line of text? If so could you please give me an example?

**Comment by xlxwalex** [comment]
Thank you for your interest in our work. Actually, I have designed a tool (website with server) for error correction in the process of modeling. It may meet your requirements. I will simplify it into a DEMO version and update it in the code. Please keep an eye on our repository.

**Comment by yuan-cherish** [comment]
Ok thanks a lot, looking forward to your subsequent contributions.

**Comment by yuan-cherish** [comment]
Yes, that's what I was looking for, thanks a lot!

**Comment by xlxwalex** [comment]
：）You're welcome
