### ISSUE TITLE
Structure of Dataset

### ISSUE THREAD

**Issue by saramoeini20** [xlxwalex/FCGEC#17]
Hi,
I'm kind of beginner at GEC and i had a question about structure of dataset because I wanted to create it myself for my work. I see the format of your data is in json and sometimes i see the M2 format or parallel file format. Are they different from each other and where should we use each one of them? if you will help me i would be thankful.

**Comment by xlxwalex** [comment]
Hi,
The format of  the data in our FCGEC is different from M2 format. We utilize operation-oriented paradigm to annotate the dataset. More details Andexamples of our data can be found in Appendix H of our paper (https://aclanthology.org/2022.findings-emnlp.137.pdf) and [`data`](https://github.com/xlxwalex/FCGEC/tree/main/data) folder.

Besides, M2 format is only utilized to compute the performances of the model with (precision, recall and F0.5 metrics), which we borrow from MuCGEC ([ChERRANT](https://github.com/HillZhang1999/MuCGEC/tree/dac5c3fbb2ce74186001f628c9da89d6ed0ded34/scorers/ChERRANT)) . You can find more details in [`scorer`](https://github.com/xlxwalex/FCGEC/tree/main/scorer) folder and  Section 4.1 in our paper.

If you want to create the data as the format in out FCGEC, you can use our [convert_seq2seq_to_operation.py](https://github.com/xlxwalex/FCGEC/blob/main/model/STG-correction/scripts/convert_seq2seq_to_operation.py) script. The details of the algorithm can be found in [README of the scripts folder](https://github.com/xlxwalex/FCGEC/tree/main/model/STG-correction/scripts) and Algorithm 1 in our paper.

If you have any question, feel free to add the comments here!

**Comment by saramoeini20** [comment]
Is convert_seq2seq_to_operation.py script just for Chinese? If i want it in another language i should modify it or it can't be used?

**Comment by saramoeini20** [comment]
And for computing the performances of the model, Just M2 format is usable in GEC tasks?

**Comment by xlxwalex** [comment]
> Is convert_seq2seq_to_operation.py script just for Chinese? If i want it in another language i should modify it or it can't be used?

Yes, the convert_seq2seq_to_operation.py script can only be utilized to convert chinese data, but you can modify it to other language (e.g., in English, you can regard each word as a character to match).

**Comment by xlxwalex** [comment]
> And for computing the performances of the model, Just M2 format is usable in GEC tasks?

Yes, for precision, recall and F0.5 metrics, the predictions and ground truths are processed to parallel form and then be converted to M2 format to compute the metrics in [ChERRANT](https://github.com/HillZhang1999/MuCGEC/tree/dac5c3fbb2ce74186001f628c9da89d6ed0ded34/scorers/ChERRANT).

**Comment by saramoeini20** [comment]
Thank you so much for your complete and timely response.

**Comment by xlxwalex** [comment]
You're welcome :)
