### ISSUE TITLE
求模型checkpoint文件

### ISSUE THREAD

**Issue by 6wuliao6** [xlxwalex/FCGEC#2]
您好！您提供的在FCGEC语料上训练好的模型checkpoint文件地址好像失效了，请问您可以再提供一个文件吗？谢谢！

**Comment by xlxwalex** [comment]
好的，我刚刚看了一下确实，我稍后把文件传到Google Drive上，晚上的时候您可以再来仓库看一下更新

**Comment by xlxwalex** [comment]
抱歉，我发现之前链接失效的原因是CDN的SSL证书过期了，我申请了新的证书，应该很快就可以用了(由于我的Google Drive没这么大的容量所以只能用之前的方式提供下载)，所以麻烦再等一下，等好了我会再次回复！

**Comment by xlxwalex** [comment]
已经恢复了，如果你点击链接进去后还是403，可以在403页面刷新网页进入下载，或直接获取链接后用下载器进行下载，如果还有问题可以回复该条

**Comment by 6wuliao6** [comment]
> 

可以啦！谢谢您！！
