### ISSUE TITLE
模型的纠错能力

### ISSUE THREAD

**Issue by zbpjlc** [xlxwalex/FCGEC#23]
当我使用inference_singleline.py时，如果我随便输入一些词，基本上都是返回原句子。
Input the incorrect sentence (q for quit):我爱李
>> corrected sentence: 我爱李

Input the incorrect sentence (q for quit):我爱北京天是安门
>> corrected sentence: 我爱北京天是安门。

**Comment by xlxwalex** [comment]
你好，

你的这些例子感觉更偏向于Spell类型的错误，我们的训练数据集FCGEC更倾向于语义类型的错误。由于STG仅在FCGEC上训练，因此其本身不太会具有修改你所述样本错误的能力。

如果需要修改你所述样本，最好使用Spell数据对模型进行训练后再进行测试
