### ISSUE TITLE
convert_fcgec_to_seq2seq.py有bug

### ISSUE THREAD

**Issue by yanghh2000** [xlxwalex/FCGEC#24]
转换为seq2seq格式的脚本有bug：在句首处的插入操作（"Insert\":"pos":-1）会被插入到句尾。
如：
source:天空和土地日益被拥挤的高楼遮蔽的时代，他们怀着忧虑之心仰望天空，守卫土地。
target: 天空和土地日益被拥挤的高楼遮蔽的时代，他们怀着忧虑之心仰望天空，守卫土地。在

**Comment by xlxwalex** [comment]
你好，

非常感谢指出这个问题，我们提交了新的代码修复了这个问题！
