### ISSUE TITLE
indep_evaluate.py Line106有bug

### ISSUE THREAD

**Issue by AugensternZX** [xlxwalex/FCGEC#33]
您修改了[data_utils.py]中的reconstruct_tagger_V2函数返回值为三个，但是调用该函数的indep_evaluate.py Line106使用两个变量接收。
![scshot](https://github.com/xlxwalex/FCGEC/assets/96071450/9cf66836-def4-40c4-9baf-75df5055d9d1)

**Comment by AugensternZX** [comment]
![jietu](https://github.com/xlxwalex/FCGEC/assets/96071450/79c46d79-d4b0-4ed9-ad7f-efd4c39e2010)

**Comment by xlxwalex** [comment]
你好，感谢反馈！

该错误是在解决[`Issue 10`](https://github.com/xlxwalex/FCGEC/issues/10)提到的问题时加入了特殊符号映射，但是后面只改动了joint版本而没有同步修改indep，造成了返回参数的问题，现在已经修复，非常感谢您的反馈！

**Comment by AugensternZX** [comment]
感谢您的回复
