### ISSUE TITLE
方便开源一下数据标注工具不，谢谢

### ISSUE THREAD

**Issue by yzhhome** [xlxwalex/FCGEC#34]
方便开源一下数据标注工具不，谢谢。

**Comment by xlxwalex** [comment]
你好，

由于我们的标注工具一开始就计划内部使用，所以在开发的时候是怎么简单怎么来的。所以很多配置以及数据库相关的模块都是写死的，因此要开源的话需要改动相当多的代码部分。

由于目前我手上有其他的项目因此可能没有时间对标注工具的代码进行整理开源，非常抱歉。您可以看看https://github.com/HumanSignal/label-studio/ 等开源标注平台，不知道它们是否能满足需求。

**Comment by yzhhome** [comment]
发一份标注工具的代码到我的邮箱( dzy113@126.com)可以不，我参考一下实现，谢谢

**Comment by xlxwalex** [comment]
我们的标注程序是用C#写的，我可以给你核心标注界面的逻辑供你参考，等整理好后会发给你

**Comment by yzhhome** [comment]
好的，谢谢

**Comment by xlxwalex** [comment]
已经通过邮件发给你了:)

**Comment by yzhhome** [comment]
非常感谢



在 2024-03-07 14:00:38，"XLXW" ***@***.***> 写道：

已经通过邮件发给你了:)

**Comment by yzhhome** [comment]
你好，这几个依赖的程序集文件麻烦再发一下，非常谢谢

在 2024-03-07 14:00:38，"XLXW" ***@***.***> 写道：

已经通过邮件发给你了:)

**Comment by xlxwalex** [comment]
Hi，

抱歉晚回复了几天，因为这个issue状态close了所以没在我这边主页显示，看到Github的邮件提醒才发现。

我稍晚一点发你：）

**Comment by xlxwalex** [comment]
已经通过邮件发给你啦，请查收：）
