### ISSUE TITLE
在线评测如何获取submission_example.zip文件

### ISSUE THREAD

**Issue by zidong-onepiece1** [xlxwalex/FCGEC#36]
You can regard "submission_example.zip" in "Starting Kit" as the example for uploading.
请问在线评测页面中的submission_example.zip，在哪里可以下载？

**Comment by xlxwalex** [comment]
你好，

之前Starting Kit字段没有设置，我刚刚已经更新了界面，请在Participate的[`Files`标签](https://codalab.lisn.upsaclay.fr/competitions/8020#participate-get_starting_kit)界面的Starting Kit获得`submission_example.zip`，内含一个`predict.json`文件可以作为上传格式的参考。

如果有其他问题，欢迎回复！

**Comment by zidong-onepiece1** [comment]
非常感谢！还有一个小问题，如果对测试集的某条句子，模型认为其没有任何语法错误，那么"error_type"应该赋哪个值，我赋值为空，在提交时遇到了key_error

Traceback (most recent call last):
  File "/tmp/codalab/tmpPsHl7I/run/program/score.py", line 143, in 
    typ[TYPE_MAP[typkey]] = 1
KeyError: ''

**Comment by xlxwalex** [comment]
如果没语病错误的话，`error_type`设为"*"就可以了
