### ISSUE TITLE
验证集指标

### ISSUE THREAD

**Issue by Yvonne-LOK** [xlxwalex/FCGEC#38]
你好！我用ChERRANT 在验证集上评估，排除掉所有正确样本、去掉所有的标点符号后，计算指标如下：
![image](https://github.com/xlxwalex/FCGEC/assets/79566199/d8c0cf4c-07fa-46c2-86db-92c41ec2ac5c)

而issue29的朋友的指标如下：
![image](https://github.com/xlxwalex/FCGEC/assets/79566199/2a50ad46-f205-4857-8058-3fc8229f29e0)

我是按照run_stg_joint.sh给出的脚本和默认参数，用本仓库首页给的ckpt推理的，但是P和F0.5值比issue29中的低了3-4个点。
想问一下我得到的指标是正常结果吗？是否是脚本里有哪个重要的参数需要我改一下，或者是因为这里的验证集又更新了？
附上我运行的脚本：
![image](https://github.com/xlxwalex/FCGEC/assets/79566199/ade23877-72d9-46b2-b112-15552beb8143)

谢谢！

**Comment by xlxwalex** [comment]
你好，

我觉得或许你可以试试看把sp_map关了看看，我不是很确定这个会不会影响到结果

**Comment by Yvonne-LOK** [comment]
感谢你的及时回复！

我记得issue10里面提到增加sp_map是用于处理标点符号的。我把sp_map设置成false之后，指标确实和ISSUE29的朋友去掉标点符号之前的指标差不多，如下图：
![image](https://github.com/xlxwalex/FCGEC/assets/79566199/a68c4211-b7b3-4aeb-80bc-a16254746989)

请问是需要不依赖sp_map参数、自己手动把数据中的标点符号去掉嘛？
谢谢！

**Comment by xlxwalex** [comment]
是的，需要手工去掉标点去对比一下，应该能和他的结果一致。

**Comment by Yvonne-LOK** [comment]
好的我试一下，非常感谢~

**Comment by Yvonne-LOK** [comment]
去掉标点后只有FP的值不一致，我的是620，如下图：
![image](https://github.com/xlxwalex/FCGEC/assets/79566199/bbbaad05-9ee4-441e-97fe-812a41ec085c)

ISSUE29的FP则是581，感觉差的还是有点多

**Comment by xlxwalex** [comment]
我这边给你一下我去掉的标点符号的集合作为参考，如下所示：
```python
"""！？｡。，,.;:《》'$%^&*()!@#~`?/\|<>"“”：；、%&……！＂＃＄％＆＇（）＊＋－／：；＜＝＞＠［＼］＾＿｀｛｜｝～｟｠｢｣､、〃》「」『』【】〔〕〖〗〘〙〚〛〜〝〞〟〰〾〿–—‘'‛“”„‟…‧﹏"""
```

因为我不是很清楚ISSUE29的朋友做的处理，因此如果还是不一致的话，你可以在ISSUE29中@可能可以讨论一下，我会把那个ISSUE在开放起来

**Comment by Yvonne-LOK** [comment]
好的好的，我再试一下~非常感谢！

**Comment by Yvonne-LOK** [comment]
@xlxwalex 你好！我用了你的标点符号集合之后，指标就一致了，非常感谢你的耐心解答！
![image](https://github.com/xlxwalex/FCGEC/assets/79566199/08ef7d5a-4d41-40da-bc0d-7548cd602bf8)

**Comment by xlxwalex** [comment]
> @xlxwalex 你好！我用了你的标点符号集合之后，指标就一致了，非常感谢你的耐心解答！ ![image](https://private-user-images.githubusercontent.com/79566199/342290221-08ef7d5a-4d41-40da-bc0d-7548cd602bf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjI5MTcsIm5iZiI6MTcxOTIyMjYxNywicGF0aCI6Ii83OTU2NjE5OS8zNDIyOTAyMjEtMDhlZjdkNWEtNGQ0MS00MGRhLWJjMGQtNzU0OGNkNjAyYmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA5NTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmM2M5YWIzZmExNDI5ODU0NmExNDA2MmM1MTQ5OGNkNmEyZDVlNWI4MTUyZDBmMDEwZDYzODM0NjBmZWU1NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-JxDR872i0y_9M2-e456XAwERaLQheN2pWETBS6Q_2g)

好的，那太棒了哈哈！
