### ISSUE TITLE
checkp变量赋值

### ISSUE THREAD

**Issue by albert587** [xlxwalex/FCGEC#4]
您好！在使用run_stg_joint.sh文件运行您提供的预训练模型的时候，发现checkp变量还未定义，我不是很清楚checkp变量的含义以及应该如何赋值，希望您不吝赐教，谢谢！

**Comment by xlxwalex** [comment]
您好，checkp的变量$JOINT_CHECK_DIR的赋值在run_stg_joint.sh脚本的第40行（如下图所示），它的意思是保存模型checkpoint文件到哪个子文件夹以此来方便实验超参数管理(其父文件夹为主目录下创建的$CHECKPOINT_DIR)，比如在run_stg_joint.sh中`$CHECKPOINT_DIR=checkpoints`，`$JOINT_CHECK_DIR=joint_model`，那么模型的checkpoint文件会保存到主目录的`checkpoints/joint_model/`目录下。
![B 1E@W8)I`S@Q{P W662S47](https://user-images.githubusercontent.com/26522478/205896048-52f1e433-ca25-4d9b-ab5e-919ba81173ee.png)

**Comment by xlxwalex** [comment]
客气啦！
