### ISSUE TITLE
发现 dev 中的一条错误标注

### ISSUE THREAD

**Issue by Jacob-Zhou** [xlxwalex/FCGEC#40]
https://github.com/xlxwalex/FCGEC/blob/5a43f232e89108181191e0400db44ac801d2258f/data/FCGEC_valid.json#L618C1-L624C7

```json
 "5b25cca009b6d248efdea5a28f9b392f": {
    "sentence": "伴随着末代港督的离去，这座古典风格的白色建筑在历经一个多世纪的风雨后，新的旗帜将飘扬在香港上空。",
    "error_flag": 1,
    "error_type": "SC",
    "operation": "[{\"Insert\":[{\"pos\":-1,\"tag\":\"INS_7\",\"label\":\"将迎来新的旗帜\"}]}]",
    "version": "FCGEC EMNLP 2022"
},
```

这条标注存在问题。

在使用[convert_fcgec_to_seq2seq.py](https://github.com/xlxwalex/FCGEC/blob/main/model/STG-correction/scripts/convert_fcgec_to_seq2seq.py)处理后的结果为：
> **将迎来新的旗帜**伴随着末代港督的离去，这座古典风格的白色建筑在历经一个多世纪的风雨后，新的旗帜将飘扬在香港上空。

**Comment by xlxwalex** [comment]
你好，

感谢指出标注错误！这里题目的正确解析为：https://easylearn.baidu.com/edu-page/tiangong/questiondetail?id=1732137184392784193&fr=search

因此应使用Modify操作，将“新的旗帜将飘扬在香港上空”改为“将迎来新的旗帜”，

我们已经标记了这个句子，将在之后和[ISSUE 25](https://github.com/xlxwalex/FCGEC/issues/25)一起修改。
