### ISSUE TITLE
CodaLab提交失败

### ISSUE THREAD

**Issue by ymliucs** [xlxwalex/FCGEC#42]
CodaLab提交后卡住了，无法进行线上评分。 @xlxwalex

**Comment by xlxwalex** [comment]
Hi,

我在后台看了一下今天没有提交的记录，Codalab平台优势和是会卡住的，一般情况下你可以刷新界面后提交一个新的结果试试，如果还是不行，欢迎回复，我再想想办法！

**Comment by ymliucs** [comment]
> Hi,
> 
> 我在后台看了一下今天没有提交的记录，Codalab平台优势和是会卡住的，一般情况下你可以刷新界面后提交一个新的结果试试，如果还是不行，欢迎回复，我再想想办法！

感谢回复！
我之前提交都是没问题的，最近两天提交的时候，点完“submit”之后，按钮变灰，然后就没反应了，刷新之后也没显示有提交结果.。之前提交的时候点击完“submit”，过几秒就按钮就恢复白色了，显示提交上去了。
我不确定是否是我的问题，有时间的话还请从网页上测试一下~

**Comment by xlxwalex** [comment]
可以提供一下你在codalab上的用户名吗

**Comment by ymliucs** [comment]
> 可以提供一下你在codalab上的用户名吗？
> 
> 我查一下submission

您好，用户名是ymliucs

**Comment by xlxwalex** [comment]
好的，我看一下

**Comment by xlxwalex** [comment]
我看了一下我这里你最近一次提交显示的是5月31日，然后我拿你5月31日的predict.json交了一版似乎可以正常跑出结果。我不知道这是不是codalab的bug

**Comment by xlxwalex** [comment]
可以截图一下你的界面吗

**Comment by ymliucs** [comment]
![image](https://github.com/user-attachments/assets/421ade57-e8c9-4cb7-b164-c2de0f419f92)

您好，就是这样，交上去之后就卡住了

**Comment by xlxwalex** [comment]
是点击Submit之后没反应吗？我刚刚交的时候也是这样，在国内的话访问界面没问题，但是需要梯子才能正常提交数据，不知道你提交的时候是否有挂梯子？

**Comment by ymliucs** [comment]
> 是点击Submit之后没反应吗？我刚刚交的时候也是这样，在国内的话访问界面没问题，但是需要梯子才能正常提交数据，不知道你提交的时候是否有挂梯子？

对对对，就是点击submit没反应。我有挂梯子的，试了几个节点都不行 :)

**Comment by xlxwalex** [comment]
要不你发一份你的结果到我邮箱里吧 xlxw@xlxw.org，我评测一下然后把结果给你？等你之后节点稳定了再自己测测看

**Comment by ymliucs** [comment]
收到，谢谢啦！
