### ISSUE TITLE
测试集中的数据全部都是含有语法错误的句子还是有部分是正确的句子

### ISSUE THREAD

**Issue by TLL1213** [xlxwalex/FCGEC#45]
假设我的训练过程中只使用了错误的句子去训练，我提交到在线评测平台去测试，这是否合理，因为我想知道 测试集中包含了正确的句子吗

**Comment by xlxwalex** [comment]
你好，

测试集中为了能够同时兼顾病句检测任务，所以是包含正确句子的，不过在Correction任务上会忽略Golden Label标注的正确句子，只会对病句样本进行比较计算指标，因此是合理的。
