### ISSUE TITLE
数据转换成平行句对

### ISSUE THREAD

**Issue by nghuyong** [xlxwalex/FCGEC#5]
如何将提供的数据集转换成平行句对： （错误句子，修正后句子）
尝试进行解析，发现还挺麻烦，存在一些不一致。比如：Insert的label为一个list，也可能为一个str
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/16462374/206190244-dad5bd57-5015-40a5-a56c-6af11e00a716.png">

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/16462374/206190436-6d9c5f83-fb2e-4b1f-8a5d-67c875dba799.png">

希望能提供一下转换脚本，或者直接转换好的数据，非常感谢

**Comment by xlxwalex** [comment]
您好，
  我们在昨天上传了转换数据为Seq2Seq格式的脚本，您可以参考使用[convert_fcgec_to_seq2seq.py](https://github.com/xlxwalex/FCGEC/blob/main/model/STG-correction/scripts/convert_fcgec_to_seq2seq.py)，您可以重新Clone后进入scripts文件夹直接python convert_fcgec_to_seq2seq.py

**Comment by nghuyong** [comment]
嗯，看到了更新的readme，感谢！！
