### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by nghuyong** [xlxwalex/FCGEC#6]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/16462374/206195732-d4272d8d-9220-4b3d-a3fb-5c158723b404.png">
train.json里面的这句话error_flag=1, 但是op是空，是没错吗？

**Comment by xlxwalex** [comment]
您好，新的训练集我已上传，请您再拉取一次！

**Comment by nghuyong** [comment]
收到，感谢
